name: AdvancedLeaderboards
main: Rushil13579\AdvancedLeaderboards\Main
api: 4.0.0
version: 1.0.1-beta
author: Rushil13579
mcpe-protocol: [554]
softdepend: [EconomyAPI,BedrockEconomy]

permissions:
  advancedleaderboards.command.lb:
    description: Allows a player to access all leaderboard commands!
    default: op
